# config/portfolio.yml
asOf: 2025-11-01
baseCurrency: EUR

benchmark: "^CAC"       # 🇫🇷 Indice CAC 40
initialCash: 10000       # Portefeuille virtuel de départ (en euros)

sectors:
  - Luxe
  - Énergie
  - Santé
  - Industrie
  - Finance
  - Technologie

constraints:
  maxLine: 0.25          # poids max d'une ligne
  maxSector: 0.5         # poids max d'un secteur

risk:
  maxConcentration: 0.35
  alertThreshold: 0.9

# ---------------------------------------------------------------------
# Recherche web réelle (Reco #2)
# ---------------------------------------------------------------------
websearch:
  provider: brave            # brave | serpapi | bing | mock
  ttlDays: 7
  maxResults: 5
  language: fr
  rateLimitPerSecond: 1
  maxRequestsPerRun: 20
  on429: fallback            # fallback | retry | error
  providerFallback: mock

# ---------------------------------------------------------------------
# Marché / sources de prix (Reco #2-bis)
# ---------------------------------------------------------------------
market:
  source: mixed             # mixed = indices via Stooq, actions via Alpha Vantage
  defaultSuffix: ".PA"       # Paris / Euronext
  benchmark: "^CAC"
  currency: EUR

providers:
  alphaVantage:
    keyEnv: ALPHA_VANTAGE_KEY
    outputSize: compact      # ou full
    minDelayMs: 15000        # 5 req/min → 15s mini
    cache:
      dir: data/_cache/alpha
      ttlDays: 7

# ---------------------------------------------------------------------
# Exemples de titres suivis (marché FR)
# ---------------------------------------------------------------------
symbols:
  # Luxe
  - MC.PA   # LVMH
  - OR.PA   # L'Oréal
  - RMS.PA  # Hermès

  # Santé
  - SAN.PA  # Sanofi
  - AI.PA   # Air Liquide

  # Énergie
  - TTE.PA  # TotalEnergies

  # Industrie
  - AIR.PA  # Airbus
  - SGO.PA  # Saint-Gobain

  # Finance
  - BNP.PA  # BNP Paribas
  - ACA.PA  # Crédit Agricole
  - GLE.PA  # Société Générale

  # Technologie / télécoms
  - CAP.PA  # Capgemini
  - ORA.PA  # Orange
  - STM.PA  # STMicroelectronics

# ---------------------------------------------------------------------
# Divers
# ---------------------------------------------------------------------
report:
  outputDir: report
  theme: light
